# GAE用
entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: 4536612319997edc4997095aad3afaabe7b2fd594156df445bbf15d0149994de0a1c5d30510a791d3b09b3653a7722ae896808347c9c272089b74dfcc5c6d6e3
  TWITTER_KEY: MXhIE0qnx06re1HXTnRcIzb5h
  TWITTER_SECRET: 1eXo1IkUwXyiiIXpRaSrgqa6gJtCNbQfMPs3Iso21uwWwJixp9
  DB_PASSWORD: hobbycartdb
  DB_USER: hobbycart
beta_settings:
  cloud_sql_instances: hobbycart-211913:asia-northeast1:hobbycartdb
