version: '3.3'
services:
  nginx:
    image: nginx
  # 本番確認用のイメージファイル
#  prod_ap:
#    image: asia.gcr.io/compact-nirvana-140509/hobbycart-production:v7
#    ports:
#      - "3001:3000"
#    stdin_open: true
#    tty: true
#    depends_on:
#      - db
#    environment:
#      RAILS_ENV: production
#      DB_PASS:
#      RAILS_SERVE_STATIC_FILES: 1
#      TWITTER_KEY: MXhIE0qnx06re1HXTnRcIzb5h
#      TWITTER_SECRET: 1eXo1IkUwXyiiIXpRaSrgqa6gJtCNbQfMPs3Iso21uwWwJixp9
#      SECRET_KEY_BASE: 4536612319997edc4997095aad3afaabe7b2fd594156df445bbf15d0149994de0a1c5d30510a791d3b09b3653a7722ae896808347c9c272089b74dfcc5c6d6e3
  ap:
    build: ./Dockerfile.develop
    volumes:
      - .:/hobbycart
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: bash -c "(bundle check || bundle install) && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/hobbycart
    depends_on:
      - db
      - db_test
      #- elasticsearch
      - redis
    environment:
      RAILS_ENV: development
  redis:
    image: redis
  db:
    image: mysql:5.7
    volumes:
      - hobbycart-db-data:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: hobbycart
      MYSQL_PASSWORD: hobbycart11
      MYSQL_DATABASE: hobbycart_development
  # GCP cloud sql
#  db_cloud:
#    image: "gcr.io/cloudsql-docker/gce-proxy"
#    command:
#      ["/cloud_sql_proxy",
#       "-instances=compact-nirvana-140509:asia-northeast1:hobbycart=tcp:0.0.0.0:3306",
#       "-credential_file=/config/compact-nirvana-140509-11f7bcd62916.json"]
#    volumes:
#      - "./compact-nirvana-140509-11f7bcd62916.json:/config/compact-nirvana-140509-11f7bcd62916.json"
#    ports:
#      - "3306:3306"
  db_test:
    image: mysql:5.7
    volumes:
      - hobbycart-test-db-data:/var/lib/mysql
    ports:
      - "4307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: hobbycart
      MYSQL_PASSWORD: hobbycart11
      MYSQL_DATABASE: hobbycart_test
  adminer:
    image: adminer
    ports:
      - 8080:8080
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
#    container_name: elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - hobbycart-esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200

volumes:
  hobbycart-db-data:
    driver: local
  hobbycart-test-db-data:
    driver: local
  hobbycart-esdata:
    driver: local
  gems:
    driver: local
